name: tunai_photo_compressor
description: "A new Flutter package project."
version: 0.0.1
homepage: https://example.com

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_image_compress: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
